In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
# import sys
# sys.path.insert(0, '../utils/')

# 存为 Gene - 环境 - 性状 的成对数据

In [3]:
import pandas as pd

ENV_path = 'normalized_ENV.xlsx'  # 很多 nan 值
Pheno_path = 'normalized_PHE.xlsx'

# Use pd.read_excel() for Excel files
ENV_CSV = pd.read_excel(ENV_path)
Pheno_CSV = pd.read_excel(Pheno_path)

print(ENV_CSV.shape, Pheno_CSV.shape)

(3235, 2712) (43151, 28)

In [ ]:
# 环境数据没有缺值
if ENV_CSV.isna().any().any():
    print("DataFrame 中存在 NaN 值")
else:
    print("DataFrame 中不存在 NaN 值")

# 检查每一列是否存在 NaN
nan_columns = ENV_CSV.columns[ENV_CSV.isna().any()].tolist()
print("包含 NaN 的列:", len(nan_columns))

# 检查每一行是否存在 NaN
nan_rows = ENV_CSV[ENV_CSV.isna().any(axis=1)]
print("包含 NaN 的行:\n", len(nan_rows))


# 检查整个 DataFrame 中 NaN 的总数
total_nans = ENV_CSV.isna().sum().sum()
print(f"整个 DataFrame 中 NaN 的总数: {total_nans}")

DataFrame 中不存在 NaN 值
包含 NaN 的列: 0
包含 NaN 的行:
 0
整个 DataFrame 中 NaN 的总数: 0

In [7]:
# 检查表型数据是否存在 NaN 值
if Pheno_CSV.isna().any().any():
    print("DataFrame 中存在 NaN 值")
else:
    print("DataFrame 中不存在 NaN 值")

# 检查每一列是否存在 NaN
nan_columns = Pheno_CSV.columns[Pheno_CSV.isna().any()].tolist()
print("包含 NaN 的列:", len(nan_columns))

# 检查每一行是否存在 NaN
nan_rows = Pheno_CSV[Pheno_CSV.isna().any(axis=1)]
print("包含 NaN 的行:", len(nan_rows))

# 检查整个 DataFrame 中 NaN 的总数
total_nans = Pheno_CSV.isna().sum().sum()
print(f"整个 DataFrame 中 NaN 的总数: {total_nans}")

# 删除所有包含 NaN 的行
Pheno_CSV_cleaned = Pheno_CSV.dropna()

# 检查删除后的 DataFrame
print("\n删除包含 NaN 的行后的 DataFrame 形状:", Pheno_CSV_cleaned.shape)

# 验证删除后是否还有 NaN 值
if Pheno_CSV_cleaned.isna().any().any():
    print("删除后 DataFrame 中仍存在 NaN 值")
else:
    print("删除后 DataFrame 中不存在 NaN 值")

Pheno_CSV_cleaned

DataFrame 中存在 NaN 值
包含 NaN 的列: 10
包含 NaN 的行: 27210
整个 DataFrame 中 NaN 的总数: 135287

删除包含 NaN 的行后的 DataFrame 形状: (15941, 28)
删除后 DataFrame 中不存在 NaN 值

,Code_ID,PlantID,Name_Code,CK,Agro.ecological.zone,Agro.ecological.zone1,Agro.ecological.zone2,Province,City,County,...,Day.to.siking,Maturity.to.day,Plant.height.cm.,Ear.Height,X100.kernels.weight,Ear.length,Yield,Kernel.number.per.row,Ear.diameter,Row.number.per.ear
0,Zm24635,24635,NL23-496,否,South-West,西南春玉米（中高海拔）组,0\NL23-496,云南省,楚雄彝族自治州,楚雄市,...,1.092564,1.359018,1.394745,1.473952,0.129245,0.636157,2.222790,0.896179,-0.803461,0.141305
1,Zm42575,42575,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,云南省,楚雄彝族自治州,楚雄市,...,-1.150714,-1.615036,-0.675540,-0.626801,0.211706,-0.957383,-1.362356,-1.344251,-0.803461,-0.390282
2,Zm20609,20609,NL23-530,否,South-West,西南春玉米（中高海拔）组,0\NL23-530,云南省,楚雄彝族自治州,楚雄市,...,-0.402955,-0.094964,-0.249305,1.031688,-1.128281,-0.715937,-0.323602,0.197550,-0.524407,-0.769988
9,Zm27757,27757,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,贵州省,毕节市,大方县,...,-0.830246,-1.218495,-1.680237,-1.013782,-1.746737,-2.068031,-2.043031,-1.031072,-2.198731,-0.466223
10,Zm41544,41544,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,贵州省,毕节市,大方县,...,-0.830246,-1.218495,-1.467119,-1.345480,-1.313818,-1.971453,-2.021743,-2.115151,-1.640623,-1.377516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43126,Zm17640,17640,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,文山州,砚山县,...,-0.830246,-2.077667,-1.284447,-1.179631,-2.859957,-0.136468,-0.699693,-0.067447,-1.640623,0.521010
43134,Zm42392,42392,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,临沧市,永德县,...,-0.509778,-1.615036,-0.462422,0.036594,-0.179983,0.636157,-0.615086,-1.609248,-0.524407,-0.086518
43135,Zm25481,25481,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,临沧市,永德县,...,-0.723423,-1.615036,-0.401532,0.921122,-0.138752,0.298133,-0.613995,-1.609248,-0.524407,-0.314341
43137,Zm23918,23918,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,广西壮族自治区,河池市,大化瑶族自治县,...,-0.402955,-1.086315,0.542274,-0.571518,2.355685,-1.150539,-0.827422,-0.308353,0.870863,1.356361
43144,Zm25018,25018,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,红河哈尼族彝族自治州,弥勒市,...,-0.402955,-1.086315,0.846728,0.865839,0.335397,0.539579,-0.411484,-0.067447,0.033701,-0.162459

In [10]:
print(len(Pheno_CSV_cleaned['Code_ID'].unique()), len(Pheno_CSV_cleaned['PlantID'].unique()))
print(len(ENV_CSV['Code_ID'].unique()), len(ENV_CSV['PlantID'].unique()))

15941 15941
3235 3235

In [5]:
# 说明是独一无二的编码 能直接用它来拼接
# ENV_CSV = ENV_CSV.drop(2238, axis=0)

,Treatment,0,1,2,3,4,5,6,7,8,...,662,663,664,665,666,667,668,669,670,671
0,BRD-A00100033,0.659111,-0.532868,0.222264,0.264058,0.023104,-0.048838,0.255671,-0.044851,-0.037224,...,0.093396,0.215362,0.063512,0.079707,0.152738,-0.305915,0.128911,0.556559,0.185070,-0.080283
1,BRD-A00267231,0.169176,-0.185285,0.084157,0.134895,0.099808,0.021720,0.118941,-0.028826,0.026509,...,-0.050770,0.095913,-0.035608,0.072296,0.014645,-0.160299,0.227531,-0.068114,0.044488,-0.079749
2,BRD-A00327403,0.132096,-0.070345,-0.066923,0.226285,-0.020545,0.170573,0.062262,-0.025033,0.035013,...,-0.027389,0.004005,0.115409,0.105822,0.055539,0.106982,0.175641,-0.135995,0.090863,-0.131708
3,BRD-A00520476,-0.003424,0.024353,0.036025,0.344950,-0.026156,0.043637,0.110658,-0.008379,0.037619,...,-0.057850,0.009160,0.020171,0.027238,-0.155332,-0.047156,0.065765,0.097753,0.019968,-0.087296
4,BRD-A00827783,0.098742,-0.071264,0.008949,0.256974,0.022009,-0.034763,0.007355,-0.050620,0.019454,...,-0.101405,0.022973,0.007716,0.141254,-0.134239,0.105439,0.028921,-0.117342,0.034065,0.002285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2233,BRD-K98157055,-0.081338,-0.022589,-0.050654,0.031865,0.035770,-0.060454,0.151053,0.059281,0.114772,...,0.177825,-0.011621,-0.149664,0.056499,-0.095153,-0.136695,-0.008704,-0.102217,-0.002807,-0.031290
2234,BRD-K98174813,-0.160617,-0.091235,-0.033795,0.043054,0.057042,-0.056063,0.060493,0.010934,0.029939,...,0.063407,-0.014496,-0.052759,0.020749,-0.018620,-0.133497,-0.066132,-0.149030,0.043032,-0.002464
2235,BRD-K98281970,0.139715,-0.143055,-0.174633,0.107044,-0.008315,0.118132,0.258252,0.015874,0.048815,...,0.122998,-0.081210,-0.202933,0.035203,-0.038211,-0.078105,-0.007540,-0.076733,0.166075,-0.039087
2236,BRD-K98297262,-0.277599,0.202855,-0.007076,-0.030692,-0.301979,-0.165271,0.285814,0.124983,0.340405,...,0.220788,-0.034219,-0.158510,0.057452,-0.280518,-0.157254,0.229366,-0.119540,-0.318411,0.333370
2237,BRD-K98521173,0.051880,-0.078683,-0.082712,0.089167,-0.084260,0.067074,0.135417,-0.013173,0.162386,...,0.014165,-0.024924,-0.208857,0.068802,-0.070271,-0.163328,0.089968,0.001258,0.062198,-0.105603

In [11]:
# 按照 'Code_ID' 列进行拼接
merged_df = pd.merge(Pheno_CSV_cleaned, ENV_CSV, on='Code_ID', how='inner')  # 默认是 inner join
merged_df

,Code_ID,PlantID_x,Name_Code_x,CK_x,Agro.ecological.zone_x,Agro.ecological.zone1_x,Agro.ecological.zone2_x,Province_x,City_x,County_x,...,SSD.235,SSD.236,SSD.237,SSD.238,SSD.239,SSD.240,SSD.241,SSD.242,SSD.243,SSD.244
0,Zm24635,24635,NL23-496,否,South-West,西南春玉米（中高海拔）组,0\NL23-496,云南省,楚雄彝族自治州,楚雄市,...,1.317441,-0.507838,-0.411183,0.150304,-1.347295,1.174180,0.122286,1.043983,-0.282808,0.627334
1,Zm42575,42575,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,云南省,楚雄彝族自治州,楚雄市,...,-4.715112,0.528912,0.538692,0.841770,1.659386,0.336582,1.637654,1.043983,0.069983,-0.741926
2,Zm20609,20609,NL23-530,否,South-West,西南春玉米（中高海拔）组,0\NL23-530,云南省,楚雄彝族自治州,楚雄市,...,-2.129732,-0.507838,0.538692,1.533236,0.907715,1.732579,0.879970,0.163023,0.069983,1.083755
3,Zm27757,27757,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,贵州省,毕节市,大方县,...,-6.438698,-0.507838,-1.361057,0.150304,-5.105646,-4.549407,-3.363061,-2.832242,-6.103853,-0.285506
4,Zm27631,27631,NL23-53,否,South-West,西南春玉米（中高海拔）组,0\NL23-53,云南省,大理白族自治州,大理市,...,-5.576905,-3.618088,-3.260805,0.841770,0.156045,1.034580,0.879970,1.043983,0.069983,1.083755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Zm43151,43151,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,贵州省,兴义市,兴义市,...,-3.853318,0.528912,-2.310931,-1.924095,-2.098965,-2.455412,-2.908450,-2.303666,-1.693970,0.718619
1684,Zm17640,17640,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,文山州,砚山县,...,-4.715112,-0.507838,-6.110428,0.841770,-0.595625,-1.757413,0.879970,-0.717937,-1.693970,-2.111187
1685,Zm42392,42392,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,临沧市,永德县,...,-2.991525,-0.507838,0.538692,0.841770,0.907715,1.034580,0.879970,1.043983,0.951959,0.627334
1686,Zm23918,23918,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,广西壮族自治区,河池市,大化瑶族自治县,...,0.455648,0.528912,0.538692,0.841770,-3.602305,0.336582,0.879970,-6.003698,-1.693970,-0.285506
1687,Zm25018,25018,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,红河哈尼族彝族自治州,弥勒市,...,0.455648,1.565663,1.488566,0.841770,0.907715,0.336582,0.122286,-3.360818,-0.811994,1.083755

# 读取基因数据，然后利用 环境中的文件来对齐。

In [13]:
# 读取 txt 文件
# 假设文件是以空格分隔的，第一列是行名，其余列是基因数据
df = pd.read_csv('ID_gen_260_12233.txt', sep=' ', header=None, index_col=0)
df

,1,2,3,4,5,6,7,8,9,10,...,12224,12225,12226,12227,12228,12229,12230,12231,12232,12233
0,,,,,,,,,,,,,,,,,,,,,
158-A,0,0,0,0,2,0,2,1,0,0,...,1,1,0,0,1,0,1,1,1,1
161-A,0,0,0,1,2,1,0,1,0,0,...,1,0,0,0,1,1,1,1,1,0
NL23-503,0,0,0,0,0,0,1,1,0,1,...,0,1,1,1,1,1,1,1,1,1
NL23-480,0,0,0,1,1,0,1,1,0,1,...,1,1,1,0,2,1,1,0,1,1
159-A,0,1,0,0,2,0,2,1,0,0,...,1,1,0,0,1,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NL23-53,0,0,0,1,1,0,1,1,0,0,...,1,1,1,0,1,1,1,1,1,1
NL23-524,0,1,0,1,0,2,2,1,0,0,...,0,1,1,0,1,1,1,0,1,1
2-A,0,0,0,0,0,2,0,1,0,0,...,1,1,1,0,1,0,1,0,1,1
NL23-453,0,0,0,1,0,0,1,1,0,0,...,0,1,1,0,1,0,1,1,1,1
171-A,0,2,0,0,1,0,2,1,0,0,...,0,1,0,0,1,1,0,1,1,1

In [21]:
print(df.index)

Index(['158-A', '161-A', 'NL23-503', 'NL23-480', '159-A', '358-A', '359-A',
       '21-A', '154-A', '162-A',
       ...
       'NL23-473', 'NL23-452', '225-A', '11-A', 'NL23-41', 'NL23-53',
       'NL23-524', '2-A', 'NL23-453', '171-A'],
      dtype='object', name=0, length=260)

In [23]:
merged_df

,Code_ID,PlantID_x,Name_Code_x,CK_x,Agro.ecological.zone_x,Agro.ecological.zone1_x,Agro.ecological.zone2_x,Province_x,City_x,County_x,...,SSD.235,SSD.236,SSD.237,SSD.238,SSD.239,SSD.240,SSD.241,SSD.242,SSD.243,SSD.244
0,Zm24635,24635,NL23-496,否,South-West,西南春玉米（中高海拔）组,0\NL23-496,云南省,楚雄彝族自治州,楚雄市,...,1.317441,-0.507838,-0.411183,0.150304,-1.347295,1.174180,0.122286,1.043983,-0.282808,0.627334
1,Zm42575,42575,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,云南省,楚雄彝族自治州,楚雄市,...,-4.715112,0.528912,0.538692,0.841770,1.659386,0.336582,1.637654,1.043983,0.069983,-0.741926
2,Zm20609,20609,NL23-530,否,South-West,西南春玉米（中高海拔）组,0\NL23-530,云南省,楚雄彝族自治州,楚雄市,...,-2.129732,-0.507838,0.538692,1.533236,0.907715,1.732579,0.879970,0.163023,0.069983,1.083755
3,Zm27757,27757,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,贵州省,毕节市,大方县,...,-6.438698,-0.507838,-1.361057,0.150304,-5.105646,-4.549407,-3.363061,-2.832242,-6.103853,-0.285506
4,Zm27631,27631,NL23-53,否,South-West,西南春玉米（中高海拔）组,0\NL23-53,云南省,大理白族自治州,大理市,...,-5.576905,-3.618088,-3.260805,0.841770,0.156045,1.034580,0.879970,1.043983,0.069983,1.083755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Zm43151,43151,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,贵州省,兴义市,兴义市,...,-3.853318,0.528912,-2.310931,-1.924095,-2.098965,-2.455412,-2.908450,-2.303666,-1.693970,0.718619
1684,Zm17640,17640,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,文山州,砚山县,...,-4.715112,-0.507838,-6.110428,0.841770,-0.595625,-1.757413,0.879970,-0.717937,-1.693970,-2.111187
1685,Zm42392,42392,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,临沧市,永德县,...,-2.991525,-0.507838,0.538692,0.841770,0.907715,1.034580,0.879970,1.043983,0.951959,0.627334
1686,Zm23918,23918,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,广西壮族自治区,河池市,大化瑶族自治县,...,0.455648,0.528912,0.538692,0.841770,-3.602305,0.336582,0.879970,-6.003698,-1.693970,-0.285506
1687,Zm25018,25018,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,红河哈尼族彝族自治州,弥勒市,...,0.455648,1.565663,1.488566,0.841770,0.907715,0.336582,0.122286,-3.360818,-0.811994,1.083755

In [24]:
# 将 df 的行索引转换为列
df_reset_index = df.reset_index()

# 检查 df_reset_index
print(df_reset_index.head())

# 合并 merged_df 和 df_reset_index
merged_all = pd.merge(merged_df, df_reset_index, left_on='Name_Code_x', right_on=0, how='inner')

# 删除多余的列（索引列）
merged_all = merged_all.drop(columns=[0])

# 打印合并后的 DataFrame
print(merged_all.head())

      0      1      2      3      4      5      6      7      8      9      \
0     158-A      0      0      0      0      2      0      2      1      0
1     161-A      0      0      0      1      2      1      0      1      0
2  NL23-503      0      0      0      0      0      0      1      1      0
3  NL23-480      0      0      0      1      1      0      1      1      0
4     159-A      0      1      0      0      2      0      2      1      0

   ...  12224  12225  12226  12227  12228  12229  12230  12231  12232  12233
0  ...      1      1      0      0      1      0      1      1      1      1
1  ...      1      0      0      0      1      1      1      1      1      0
2  ...      0      1      1      1      1      1      1      1      1      1
3  ...      1      1      1      0      2      1      1      0      1      1
4  ...      1      1      0      0      1      0      1      1      1      1

[5 rows x 12234 columns]
   Code_ID  PlantID_x Name_Code_x CK_x Agro.ecological.zone_x  \
0  Zm24635      24635    NL23-496    否             South-West
1  Zm42575      42575    NL23-497    否             South-West
2  Zm20609      20609    NL23-530    否             South-West
3  Zm27757      27757    NL23-497    否             South-West
4  Zm27631      27631     NL23-53    否             South-West

  Agro.ecological.zone1_x Agro.ecological.zone2_x Province_x   City_x  \
0            西南春玉米（中高海拔）组              0\NL23-496        云南省  楚雄彝族自治州
1            西南春玉米（中高海拔）组              0\NL23-497        云南省  楚雄彝族自治州
2            西南春玉米（中高海拔）组              0\NL23-530        云南省  楚雄彝族自治州
3            西南春玉米（中高海拔）组              0\NL23-497        贵州省      毕节市
4            西南春玉米（中高海拔）组               0\NL23-53        云南省  大理白族自治州

  County_x  ...  12224 12225 12226  12227 12228 12229 12230  12231  12232  \
0      楚雄市  ...      1     1     1      0     1     0     1      1      1
1      楚雄市  ...      1     1     1      0     0     1     0      1      1
2      楚雄市  ...      1     1     1      0     1     1     1      0      1
3      大方县  ...      1     1     1      0     0     1     0      1      1
4      大理市  ...      1     1     1      0     1     1     1      1      1

   12233
0      1
1      1
2      1
3      1
4      1

[5 rows x 14972 columns]

In [25]:
merged_all

,Code_ID,PlantID_x,Name_Code_x,CK_x,Agro.ecological.zone_x,Agro.ecological.zone1_x,Agro.ecological.zone2_x,Province_x,City_x,County_x,...,12224,12225,12226,12227,12228,12229,12230,12231,12232,12233
0,Zm24635,24635,NL23-496,否,South-West,西南春玉米（中高海拔）组,0\NL23-496,云南省,楚雄彝族自治州,楚雄市,...,1,1,1,0,1,0,1,1,1,1
1,Zm42575,42575,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,云南省,楚雄彝族自治州,楚雄市,...,1,1,1,0,0,1,0,1,1,1
2,Zm20609,20609,NL23-530,否,South-West,西南春玉米（中高海拔）组,0\NL23-530,云南省,楚雄彝族自治州,楚雄市,...,1,1,1,0,1,1,1,0,1,1
3,Zm27757,27757,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,贵州省,毕节市,大方县,...,1,1,1,0,0,1,0,1,1,1
4,Zm27631,27631,NL23-53,否,South-West,西南春玉米（中高海拔）组,0\NL23-53,云南省,大理白族自治州,大理市,...,1,1,1,0,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Zm43151,43151,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,贵州省,兴义市,兴义市,...,0,1,0,0,0,1,1,0,1,1
1684,Zm17640,17640,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,文山州,砚山县,...,0,1,0,0,0,1,1,0,1,1
1685,Zm42392,42392,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,临沧市,永德县,...,0,1,0,0,0,1,1,0,1,1
1686,Zm23918,23918,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,广西壮族自治区,河池市,大化瑶族自治县,...,0,1,0,0,0,1,1,0,1,1
1687,Zm25018,25018,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,红河哈尼族彝族自治州,弥勒市,...,0,1,0,0,0,1,1,0,1,1

In [27]:
# 检查整个 DataFrame 中是否存在 NaN
if merged_all.isna().any().any():
    print("DataFrame 中存在 NaN 值")
else:
    print("DataFrame 中不存在 NaN 值")

# # 检查每一列是否存在 NaN
# nan_columns = merged_df.columns[merged_df.isna().any()].tolist()
# print("包含 NaN 的列:", len(nan_columns))

# # 检查每一行是否存在 NaN
# nan_rows = merged_df[merged_df.isna().any(axis=1)]
# print("包含 NaN 的行:\n", len(nan_rows))


# # 检查整个 DataFrame 中 NaN 的总数
# total_nans = merged_df.isna().sum().sum()
# print(f"整个 DataFrame 中 NaN 的总数: {total_nans}")

DataFrame 中不存在 NaN 值

In [37]:
# 保存为 CSV 文件
# merged_all.to_csv('BJUT_all.csv', index=False)  # index=False 表示不保存行索引

merged_all.to_excel('BJUT_all.xlsx', index=False)  # index=False 表示不保存行索引

In [29]:

# 将 DataFrame 转换为 NumPy 数组
numpy_array = merged_all.to_numpy()

# 保存为 NPY 文件
np.save('BJUT_all.npy', numpy_array)

# 删除很多无用列

In [30]:
merged_all

,Code_ID,PlantID_x,Name_Code_x,CK_x,Agro.ecological.zone_x,Agro.ecological.zone1_x,Agro.ecological.zone2_x,Province_x,City_x,County_x,...,12224,12225,12226,12227,12228,12229,12230,12231,12232,12233
0,Zm24635,24635,NL23-496,否,South-West,西南春玉米（中高海拔）组,0\NL23-496,云南省,楚雄彝族自治州,楚雄市,...,1,1,1,0,1,0,1,1,1,1
1,Zm42575,42575,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,云南省,楚雄彝族自治州,楚雄市,...,1,1,1,0,0,1,0,1,1,1
2,Zm20609,20609,NL23-530,否,South-West,西南春玉米（中高海拔）组,0\NL23-530,云南省,楚雄彝族自治州,楚雄市,...,1,1,1,0,1,1,1,0,1,1
3,Zm27757,27757,NL23-497,否,South-West,西南春玉米（中高海拔）组,0\NL23-497,贵州省,毕节市,大方县,...,1,1,1,0,0,1,0,1,1,1
4,Zm27631,27631,NL23-53,否,South-West,西南春玉米（中高海拔）组,0\NL23-53,云南省,大理白族自治州,大理市,...,1,1,1,0,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Zm43151,43151,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,贵州省,兴义市,兴义市,...,0,1,0,0,0,1,1,0,1,1
1684,Zm17640,17640,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,文山州,砚山县,...,0,1,0,0,0,1,1,0,1,1
1685,Zm42392,42392,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,临沧市,永德县,...,0,1,0,0,0,1,1,0,1,1
1686,Zm23918,23918,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,广西壮族自治区,河池市,大化瑶族自治县,...,0,1,0,0,0,1,1,0,1,1
1687,Zm25018,25018,NL23-477,否,Tropical,热带亚热带玉米组,Tropical\NL23-477,云南省,红河哈尼族彝族自治州,弥勒市,...,0,1,0,0,0,1,1,0,1,1

In [31]:
df_numeric = merged_all.select_dtypes(include=[np.number])
df_numeric

,PlantID_x,Adcode_x,Year_x,Day.to.tassel,Day.to.siking,Maturity.to.day,Plant.height.cm.,Ear.Height,X100.kernels.weight,Ear.length,...,12224,12225,12226,12227,12228,12229,12230,12231,12232,12233
0,24635,532301,2022,1.010629,1.092564,1.359018,1.394745,1.473952,0.129245,0.636157,...,1,1,1,0,1,0,1,1,1,1
1,42575,532301,2021,-1.072215,-1.150714,-1.615036,-0.675540,-0.626801,0.211706,-0.957383,...,1,1,1,0,0,1,0,1,1,1
2,20609,532301,2020,-0.447362,-0.402955,-0.094964,-0.249305,1.031688,-1.128281,-0.715937,...,1,1,1,0,1,1,1,0,1,1
3,27757,520521,2021,-0.759788,-0.830246,-1.218495,-1.680237,-1.013782,-1.746737,-2.068031,...,1,1,1,0,0,1,0,1,1,1
4,27631,532901,2020,1.010629,0.985741,1.226838,-0.553759,0.368292,0.685855,0.346422,...,1,1,1,0,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,43151,522301,2021,-0.968073,-0.937069,-2.209847,-1.375783,-0.903216,-0.901514,-1.053961,...,0,1,0,0,0,1,1,0,1,1
1684,17640,532622,2021,-0.863930,-0.830246,-2.077667,-1.284447,-1.179631,-2.859957,-0.136468,...,0,1,0,0,0,1,1,0,1,1
1685,42392,530923,2020,-0.551504,-0.509778,-1.615036,-0.462422,0.036594,-0.179983,0.636157,...,0,1,0,0,0,1,1,0,1,1
1686,23918,451229,2020,-0.239077,-0.402955,-1.086315,0.542274,-0.571518,2.355685,-1.150539,...,0,1,0,0,0,1,1,0,1,1
1687,25018,532504,2020,-0.239077,-0.402955,-1.086315,0.846728,0.865839,0.335397,0.539579,...,0,1,0,0,0,1,1,0,1,1

In [39]:
# 获取列名
column_names = merged_all.columns.tolist()

# 将列名保存到 txt 文件
with open('column_names.txt', 'w') as file:
    for col in column_names:
        file.write(str(col) + '\n')  # 将 col 转换为字符串后再相加

In [45]:
# 加载数据
all_data = np.load('BJUT_all.npy', allow_pickle=True)

# 定义一个函数，用于替换非数值为 0
def replace_non_numeric_with_zero(data):
    # 创建一个与 data 形状相同的数组，初始化为 0
    processed_data = np.zeros_like(data, dtype=np.float32)
    
    # 遍历每个元素
    for i in range(data.shape[0]):
        for j in range(data.shape[1]):
            # 检查元素是否为数值类型
            if isinstance(data[i, j], (int, float)):
                processed_data[i, j] = data[i, j]  # 保留数值
            else:
                processed_data[i, j] = 0  # 非数值替换为 0
    return processed_data

# 处理数据
processed_data = replace_non_numeric_with_zero(all_data)

# 保存处理后的数据（可选）
np.save('BJUT_all_processed.npy', processed_data)

In [48]:
import torch

all_data = np.load('BJUT_all_processed.npy', allow_pickle=True)

smiles = torch.tensor(all_data[:, 18:28], dtype=torch.float32)
# # 数据填充，nan to 0, 不然loss一直是nan
# self.GE_data = torch.nan_to_num(self.GE_data, nan=0.0)

GE_data = torch.tensor(all_data[:, 45:], dtype=torch.float32)  # 977 gene
smiles

tensor([[ 1.0926,  1.3590,  1.3947,  ...,  0.8962, -0.8035,  0.1413],
        [-1.1507, -1.6150, -0.6755,  ..., -1.3443, -0.8035, -0.3903],
        [-0.4030, -0.0950, -0.2493,  ...,  0.1976, -0.5244, -0.7700],
        ...,
        [-0.5098, -1.6150, -0.4624,  ..., -1.6092, -0.5244, -0.0865],
        [-0.4030, -1.0863,  0.5423,  ..., -0.3084,  0.8709,  1.3564],
        [-0.4030, -1.0863,  0.8467,  ..., -0.0674,  0.0337, -0.1625]])

In [49]:
GE_data

tensor([[2.2052, 2.0770, 1.7748,  ..., 1.0000, 1.0000, 1.0000],
        [2.1071, 1.8065, 1.5804,  ..., 1.0000, 1.0000, 1.0000],
        [2.2752, 1.3197, 1.3342,  ..., 0.0000, 1.0000, 1.0000],
        ...,
        [1.8969, 1.5361, 1.2565,  ..., 0.0000, 1.0000, 1.0000],
        [2.0090, 1.5766, 0.5437,  ..., 0.0000, 1.0000, 1.0000],
        [2.3453, 1.7795, 0.4659,  ..., 0.0000, 1.0000, 1.0000]])

# 检查异常数值

In [ ]:
# 加载数据
all_data = np.load('BJUT_all.npy', allow_pickle=True)

# 假设列名是一个列表（如果没有列名，可以用索引代替）
column_names = [f'Column_{i}' for i in range(all_data.shape[1])]  # 生成列名，例如 Column_0, Column_1, ...

# 遍历每一列
for col_idx in range(all_data.shape[1]):
    column_data = all_data[:, col_idx]  # 提取当前列的数据
    
    # 检查列中是否包含非数值类型的数据
    non_numeric_values = []
    for row_idx, value in enumerate(column_data):
        if not isinstance(value, (int, float)):  # 检查是否为非数值类型
            non_numeric_values.append((row_idx, value))  # 记录行索引和值
    
    # 如果当前列包含非数值类型的数据，打印列名和这些值
    if non_numeric_values:
        print(f"列名: {column_names[col_idx]}")
        print("非数值类型的值及其行索引:")
        # for row_idx, value in non_numeric_values:
        #     print(f"  行 {row_idx}: {value}")
        print("-" * 50)  # 分隔线

列名: Column_0
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_2
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_3
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_4
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_5
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_6
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_7
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_8
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_9
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_11
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_12
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_14
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_15
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_16
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_29
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_30
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_31
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_32
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_33
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_34
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_35
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_36
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_37
非数值类型的值及其行索引:
--------------------------------------------------
列名: Column_41
非数值类型的值及其行索引:
--------------------------------------------------

In [ ]:
import numpy as np
if np.isnan(data).any() or np.isinf(data).any():
    print("数据包含 NaN 或 inf！")